// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

declare global {
  interface Window {
    __PUBLIC_SUPABASE_CONFIG__?: {
      url?: string;
      publishableKey?: string;
    };
  }
}

export function getSupabaseEnv() {
  // 1. Check window.__PUBLIC_SUPABASE_CONFIG__ injected at runtime by SSR/Cloudflare Worker
  const runtimeUrl =
    typeof window !== "undefined" && window.__PUBLIC_SUPABASE_CONFIG__?.url
      ? window.__PUBLIC_SUPABASE_CONFIG__.url
      : "";
  const runtimeKey =
    typeof window !== "undefined" && window.__PUBLIC_SUPABASE_CONFIG__?.publishableKey
      ? window.__PUBLIC_SUPABASE_CONFIG__.publishableKey
      : "";

  // 2. Check Vite build-time env or Node/Edge process.env
  const buildUrl =
    (typeof import.meta !== "undefined" && import.meta.env?.VITE_SUPABASE_URL) ||
    (typeof process !== "undefined" &&
      (process.env?.VITE_SUPABASE_URL || process.env?.SUPABASE_URL)) ||
    "";
  const buildKey =
    (typeof import.meta !== "undefined" &&
      (import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
        import.meta.env?.VITE_SUPABASE_ANON_KEY)) ||
    (typeof process !== "undefined" &&
      (process.env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
        process.env?.SUPABASE_PUBLISHABLE_KEY ||
        process.env?.SUPABASE_ANON_KEY ||
        process.env?.VITE_SUPABASE_ANON_KEY)) ||
    "";

  const url = (runtimeUrl || buildUrl || "").trim();
  const key = (runtimeKey || buildKey || "").trim();

  return { url, key };
}

export function isSupabaseReady(): boolean {
  const { url, key } = getSupabaseEnv();
  return Boolean(url && key);
}

export const isSupabaseConfigured = isSupabaseReady();

let warnedAboutMissingEnv = false;
let loggedDiagnostic = false;

function logSupabaseRuntimeDiagnostic(url: string, key: string) {
  if (loggedDiagnostic || typeof window === "undefined") return;
  loggedDiagnostic = true;

  let supabaseHost: string | null = null;
  if (url) {
    try {
      supabaseHost = new URL(url).hostname;
    } catch {
      supabaseHost = "invalid-url";
    }
  }

  console.info("[Supabase Runtime]", {
    configured: Boolean(url && key),
    supabaseHost,
    hasPublishableKey: Boolean(key),
    origin: window.location.origin,
  });
}

function createSupabaseClient() {
  const { url, key } = getSupabaseEnv();
  logSupabaseRuntimeDiagnostic(url, key);

  if (typeof window !== "undefined") {
    console.info("[Supabase Client]", {
      instanceCreated: true,
      configured: Boolean(url && key),
      origin: window.location.origin,
    });
  }

  if (!url || !key) {
    if (!warnedAboutMissingEnv && typeof window !== "undefined") {
      warnedAboutMissingEnv = true;
      console.warn(
        "[Supabase] Production public environment configuration is not set. Devotional portal running in client-safe offline mode.",
      );
    }
    // Return a safe mock client that intercepts all calls gracefully without touching any placeholder domains
    return createClient<Database>("https://auth-offline.local", "offline-dummy-key", {
      global: {
        fetch: () =>
          Promise.resolve(
            new Response(
              JSON.stringify({
                error: "auth_unavailable",
                message: "Authentication is not configured.",
              }),
              { status: 503, headers: { "Content-Type": "application/json" } },
            ),
          ),
      },
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
    });
  }

  return createClient<Database>(url, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "implicit",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

function getSupabaseClientInstance(): ReturnType<typeof createSupabaseClient> {
  if (!_supabase) {
    _supabase = createSupabaseClient();
  } else {
    // If config was injected after initial module evaluation, upgrade offline client with real credentials
    const { url, key } = getSupabaseEnv();
    if (
      url &&
      key &&
      (_supabase as unknown as { supabaseUrl?: string })?.supabaseUrl ===
        "https://auth-offline.local"
    ) {
      _supabase = createSupabaseClient();
    }
  }
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop) {
    const client = getSupabaseClientInstance();
    const val = Reflect.get(client, prop);
    return typeof val === "function" ? val.bind(client) : val;
  },
});
