// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { ensureServerEnv, getServerEnv, getPublicSupabaseEnv } from "@/lib/server-env";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export function isServiceRoleKey(key: string | undefined): boolean {
  if (!key) return false;
  if (key.startsWith("sb_secret_")) return true;
  if (key.includes(".")) {
    const parts = key.split(".");
    if (parts.length === 3) {
      try {
        const payload = JSON.parse(Buffer.from(parts[1], "base64").toString());
        return payload.role === "service_role";
      } catch {
        return false;
      }
    }
  }
  return false;
}

export function hasValidServiceRoleKey(): boolean {
  ensureServerEnv();
  const key = getServerEnv("SUPABASE_SERVICE_ROLE_KEY");
  return isServiceRoleKey(key);
}

// 1. Privileged Server Client (service-role - bypasses RLS)
// SECURITY: Server-only. Used for background jobs (cron) that have no user session.
function createSupabaseAdminClient() {
  ensureServerEnv();
  const SUPABASE_URL =
    getServerEnv("SUPABASE_URL") || process.env.VITE_SUPABASE_URL || "https://auth-offline.local";
  const SUPABASE_SERVICE_ROLE_KEY = getServerEnv("SUPABASE_SERVICE_ROLE_KEY");

  const isLegit = isServiceRoleKey(SUPABASE_SERVICE_ROLE_KEY);
  if (!isLegit && typeof process !== "undefined" && process.env.NODE_ENV !== "test") {
    console.warn(
      "[supabaseAdmin] WARNING: SUPABASE_SERVICE_ROLE_KEY is not a valid service_role key. Background operations requiring RLS bypass (e.g. cron) will fail RLS checks.",
    );
  }

  const key = SUPABASE_SERVICE_ROLE_KEY || "offline-service-key";

  return createClient<Database>(SUPABASE_URL, key, {
    global: {
      fetch: createSupabaseFetch(key),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

// 2. Public Server Client (anon/publishable key - obeys RLS)
// Safe for general server routes and unauthenticated read-only server actions.
function createSupabaseServerClient() {
  const { url, publishableKey } = getPublicSupabaseEnv();
  const targetUrl = url || "https://auth-offline.local";
  const targetKey = publishableKey || "offline-anon-key";

  return createClient<Database>(targetUrl, targetKey, {
    global: {
      fetch: createSupabaseFetch(targetKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseServer: ReturnType<typeof createSupabaseServerClient> | undefined;

export const supabaseServer = new Proxy({} as ReturnType<typeof createSupabaseServerClient>, {
  get(_, prop, receiver) {
    if (!_supabaseServer) _supabaseServer = createSupabaseServerClient();
    return Reflect.get(_supabaseServer, prop, receiver);
  },
});
